type: view
name: product_sales
model_name: zenlytic_managed
sql_table_name: product_sales
default_date: sale_date
identifiers:
  - name: sale_id
    type: primary
    sql: ${sale_id}
    allowed_fanouts: []
  - name: product_type_id
    type: foreign
    sql: ${product_type_id}
    allowed_fanouts: []
fields:
  - name: sale_id
    field_type: dimension
    type: string
    sql: ${TABLE}."SALE_ID"
    searchable: true
    primary_key: true

  - name: product_type_id
    field_type: dimension
    type: number
    sql: ${TABLE}."PRODUCT_TYPE_ID"
    searchable: true

  - name: amount
    field_type: dimension
    type: number
    sql: ${TABLE}."AMOUNT"
    searchable: true

  - name: sale_date
    field_type: dimension_group
    type: time
    sql: ${TABLE}."SALE_DATE"
    timeframes:
      - date
      - week
      - month
      - quarter
      - year
      - day_of_year
      - week_of_year
      - month_of_year
