version: 1
type: view
name: products
model_name: pure_organics
sql_table_name: DEMO_PROD.PRODUCTS
default_date: order_lines.order
identifiers:
  - name: product_id
    type: primary
    sql: ${product_id}
fields:
  - name: product_id
    field_type: dimension
    type: string
    hidden: true
    primary_key: true
    description: The id of the product.
    sql: ${TABLE}.PRODUCT_ID
    zoe_description: The id of the product.
    searchable: false

  - name: product_type
    field_type: dimension
    type: string
    hidden: true
    primary_key: false
    description: 'The type of the product sold (Eye, Face, Lip, etc) '
    tiers: null
    sql: ${TABLE}.PRODUCT_TYPE
    searchable: true
    synonyms: []
    zoe_description: 'The type of the product. '

  - name: product_title
    field_type: dimension
    type: string
    hidden: true
    primary_key: false
    description: The title of the product sold (Everyday SPF Cream, etc)
    tiers: null
    sql: ${TABLE}.PRODUCT_TITLE
    searchable: true
    synonyms: []

  - name: product_image_url
    field_type: dimension
    type: string
    description: Product image url for the product title
    hidden: true
    primary_key: false
    searchable: false
    sql: >+
      CASE ${product_title}

      when 'Easygoing Lipstick' then
      'https://exq-art-data.s3.us-east-1.amazonaws.com/easygoing_lipstick.jpg'
      when 'Everyday Bronzer' then
      'https://exq-art-data.s3.us-east-1.amazonaws.com/everyday_bronzer.jpg'
      when 'Everyday Concealer' then
      'https://exq-art-data.s3.us-east-1.amazonaws.com/everyday_concealer.jpg'
      when 'Everyday Eyeshadow' then
      'https://exq-art-data.s3.us-east-1.amazonaws.com/everyday_eyeshadow.jpg'
      when 'Everyday SPF Cream' then
      'https://exq-art-data.s3.us-east-1.amazonaws.com/everyday_spf_cream.jpg'
      when 'Glam Lipstick' then
      'https://exq-art-data.s3.us-east-1.amazonaws.com/glam_lipstick.jpg' when
      'Luxury Blush' then
      'https://exq-art-data.s3.us-east-1.amazonaws.com/lux_blush.jpg' when
      'Luxury Eyeliner' then
      'https://exq-art-data.s3.us-east-1.amazonaws.com/lux_eyeliner.jpg' when
      'NoChap Lip Gloss SPF 15' then
      'https://exq-art-data.s3.us-east-1.amazonaws.com/spf_lip_gloss.jpg' when
      'Organic Color Correct' then
      'https://exq-art-data.s3.us-east-1.amazonaws.com/organic_color_correct.jpg'
      when 'Organic Foundation' then
      'https://exq-art-data.s3.us-east-1.amazonaws.com/organic_foundation.jpg'
      when 'Your Fav Primer' then
      'https://exq-art-data.s3.us-east-1.amazonaws.com/organic_color_correct.jpg'
      END

    synonyms: []
    tiers: null

  - name: price
    field_type: dimension
    type: string
    description: The Price of the Product
    sql: ${TABLE}.PRICE
    searchable: true

  - name: kcjjjfvusepnhnohvdhjxmacyesdodybdangzdpw
    field_type: dimension
    type: string
    description: 'The type of the product sold (Eye, Face, Lip, etc) '
    hidden: true
    label: Duplicate Product Type NJM
    primary_key: false
    searchable: true
    sql: ${TABLE}.PRODUCT_TYPE
    synonyms: []
    tiers: null
    zoe_description: 'The type of the product. '

  - name: service_type_giuqzprs
    field_type: dimension
    type: string
    label: Service Type
    sql: >-
      CASE WHEN ${products.kcjjjfvusepnhnohvdhjxmacyesdodybdangzdpw} = 'Face'
      THEN 'Skincare Consultation' WHEN
      ${products.kcjjjfvusepnhnohvdhjxmacyesdodybdangzdpw} = 'Lip' THEN 'Lip
      Color Matching' WHEN ${products.kcjjjfvusepnhnohvdhjxmacyesdodybdangzdpw}
      = 'Eye' THEN 'Eye Makeup Application' WHEN
      ${products.kcjjjfvusepnhnohvdhjxmacyesdodybdangzdpw} = 'Cheek' THEN
      'Complexion Service' END
    canon_date: order_lines.order

  - name: product_line_pwspmicd
    field_type: dimension
    type: string
    label: Product Line
    sql: >-
      CASE WHEN ${products.product_title} LIKE '%Luxury%' THEN 'Les Beiges
      Collection' WHEN ${products.product_title} LIKE '%Everyday%' THEN 'Chance
      Collection' WHEN ${products.product_title} LIKE '%Easygoing%' OR
      ${products.product_title} LIKE '%Glam%' THEN 'Rouge Coco Collection' ELSE
      'Specialty Collection' END
    canon_date: order_lines.order

  - name: service_duration_wpbknogu
    field_type: dimension
    type: string
    label: Service Duration
    sql: >-
      CASE WHEN ${products.kcjjjfvusepnhnohvdhjxmacyesdodybdangzdpw} = 'Face'
      THEN '90 minutes' WHEN
      ${products.kcjjjfvusepnhnohvdhjxmacyesdodybdangzdpw} = 'Eye' THEN '60
      minutes' WHEN ${products.kcjjjfvusepnhnohvdhjxmacyesdodybdangzdpw} = 'Lip'
      THEN '45 minutes' WHEN
      ${products.kcjjjfvusepnhnohvdhjxmacyesdodybdangzdpw} = 'Cheek' THEN '30
      minutes' END
    canon_date: order_lines.order

  - name: chanel_product_type_nixetsjf
    field_type: dimension
    type: string
    label: Chanel Product Type
    sql: >-
      CASE WHEN ${products.kcjjjfvusepnhnohvdhjxmacyesdodybdangzdpw} = 'Cheek'
      THEN 'Joues' WHEN ${products.kcjjjfvusepnhnohvdhjxmacyesdodybdangzdpw} =
      'Lip' THEN 'Lèvres' WHEN
      ${products.kcjjjfvusepnhnohvdhjxmacyesdodybdangzdpw} = 'Face' THEN 'Teint'
      WHEN ${products.kcjjjfvusepnhnohvdhjxmacyesdodybdangzdpw} = 'Eye' THEN
      'Yeux' ELSE 'Collection' END
    canon_date: order_lines.order

  - name: chanel_product_title_fnrjnvlw
    field_type: dimension
    type: string
    label: Chanel Product Title
    sql: >-
      CASE WHEN ${products.product_title} = 'Luxury Blush' THEN 'Rouge Allure
      Blush' WHEN ${products.product_title} = 'Luxury Eyeliner' THEN 'Stylo Yeux
      Élégance' WHEN ${products.product_title} = 'Everyday SPF Cream' THEN
      'Crème Lumière SPF' WHEN ${products.product_title} = 'Everyday Eyeshadow'
      THEN 'Ombre Première' WHEN ${products.product_title} = 'Organic Color
      Correct' THEN 'Correcteur Sublime' WHEN ${products.product_title} =
      'Organic Foundation' THEN 'Teint Haute Couture' WHEN
      ${products.product_title} = 'Easygoing Lipstick' THEN 'Rouge Coco Baume'
      WHEN ${products.product_title} = 'Glam Lipstick' THEN 'Rouge Coco Glamour'
      WHEN ${products.product_title} = 'NoChap Lip Gloss SPF 15' THEN 'Brillant
      Lèvres SPF 15' ELSE 'Édition Spéciale' END
    canon_date: order_lines.order

  - name: count_products
    field_type: measure
    type: count_distinct
    label: Count of Products
    sql: ${product_id}
