base_view: candy_shop_orders
model_name: zenlytic_managed
label: Candy Shop Orders
description: ''
views:
  candy_shop_order_items:
    join:
      join_type: left_outer
      relationship: many_to_one
      sql_on: >-
        ${candy_shop_orders.actual_delivery}=${candy_shop_order_items.order_item_id}
type: topic
