type: topic
label: Marketing Spend Analysis
base_view: marketing_spend
model_name: pure_organics
description: >-
  This view encapsulates data related to marketing expenses across various
  channels and sources. It provides insights into different campaigns by
  detailing the total marketing spend, cost per acquisition (CAC), cost per
  click (CPC), return on ad spend (ROAS), and profit on ad spend (PROAS). Key
  fields include the marketing channel, the source of spend, and specific
  campaign identifiers, all crucial for analyzing the efficiency and
  effectiveness of marketing investments.

hidden: false
views: {}
