base_view: marvel_rivals_heroes
description: 'The different heroes available to play in marvel rivals. '
label: Marvel Rivals Heroes
model_name: zenlytic_managed
views:
  marvel_rivals_players:
    join:
      join_type: left_outer
      relationship: one_to_many
      sql_on: >-
        ${marvel_rivals_heroes.hero_id}=${marvel_rivals_players.favorite_hero_id}
  marvel_rivals_matches:
    join:
      join_type: left_outer
      relationship: one_to_many
      sql_on: >-
        ${marvel_rivals_players.player_id}=${marvel_rivals_matches.mvp_player_id}
  marvel_rivals_match_players:
    join:
      join_type: left_outer
      relationship: one_to_many
      sql_on: >-
        ${marvel_rivals_players.player_id}=${marvel_rivals_match_players.match_player_id}
type: topic
