base_view: ltv
label: My LTV
model_name: pure_organics
views:
  customers:
    join:
      join_type: left_outer
      relationship: many_to_one
      sql_on: ${ltv.CUSTOMER_ID}=${customers.customer_id}
type: topic
