base_view: supermarket_sales
label: My new topic
model_name: zenlytic_managed
views:
  order_lines:
    join:
      join_type: left_outer
      relationship: many_to_one
      sql_on: ${supermarket_sales.Invoice ID}=${order_lines.order_line_id}
type: topic
