type: topic
label: Products Overview
base_view: products
model_name: pure_organics
<<<<<<< HEAD
description: >-
  The Products Overview captures essential information about the items available
  in an inventory or catalog. It includes: PRODUCT_TYPE, which defines the
  category or kind of product; PRODUCT_TITLE, offering a clear name or title for
  the product; PRODUCT_IMAGE_URL, providing a link to an image representing the
  product; PRICE, indicating the cost of the product; and COUNT_PRODUCTS,
  showing the quantity of these products available. This data is crucial for
  managing inventory, setting pricing strategies, and enhancing the shopping
  experience for customers.
zoe_description: >-
  The Products Overview includes product details such as type, title, image URL,
  price, and count. Use this to retrieve product-related information, manage
=======
description: 'The Products Overview captures essential information about the items
  available in an inventory or catalog. It includes: PRODUCT_TYPE, which defines the
  category or kind of product; PRODUCT_TITLE, offering a clear name or title for the
  product; PRODUCT_IMAGE_URL, providing a link to an image representing the product;
  PRICE, indicating the cost of the product; and COUNT_PRODUCTS, showing the quantity
  of these products available. This data is crucial for managing inventory, setting
  pricing strategies, and enhancing the shopping experience for customers.'
zoe_description: The Products Overview includes product details such as type, title,
  image URL, price, and count. Use this to retrieve product-related information, manage
>>>>>>> 067d8d1e8c4348038628154c5737e7e115a27efb
  inventory, and support pricing strategies.
hidden: false
views: {}
